# Generated by Django 4.0.4 on 2022-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('speed', models.FloatField()),
                ('audio_speed', models.FileField(blank=True, null=True, upload_to='audio_x/')),
            ],
        ),
    ]
