# Generated by Django 4.0.4 on 2022-06-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_extract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_extract',
            old_name='audio_speed',
            new_name='audio_extract',
        ),
    ]
